apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
   name: ibm-powervs-block-csi-driver-operator
   namespace: openshift-cloud-credential-operator
   annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  secretRef:
     name: ibm-cloud-credentials
     namespace: openshift-cluster-csi-drivers
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
      - attributes:
          - name: serviceName
            value: is
        roles:
          - crn:v1:bluemix:public:iam::::role:Operator
          - crn:v1:bluemix:public:iam::::role:Editor
          - crn:v1:bluemix:public:iam::::role:Viewer
      - attributes:
          - name: resourceType
            value: resource-group
        roles:
          - crn:v1:bluemix:public:iam::::role:Viewer
