apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: vmware-vsphere-csi-driver-operator-metrics-serving-cert
  labels:
    app: vmware-vsphere-csi-driver-operator-metrics
  name: vmware-vsphere-csi-driver-operator-metrics
  namespace: openshift-cluster-csi-drivers
spec:
  ports:
  - name: vsphere-omp
    port: 8445
    protocol: TCP
    targetPort: vsphere-omp
  selector:
    name: vmware-vsphere-csi-driver-operator
  sessionAffinity: None
  type: ClusterIP
